Repository getsentry/relay, pull requests merged in 2023-05, with the labels that each got.

#2084 build: Use jemalloc on Linux
  CHANGELOG.md
  Cargo.lock
  relay/Cargo.toml
  relay/src/main.rs
Labels: filler, maintenance

#2085 build: Bump tempfile to remove flagged dependency
  Cargo.lock
  relay-aws-extension/Cargo.toml
  relay-metrics/Cargo.toml
  relay-server/Cargo.toml
  relay-system/Cargo.toml
  relay-test/Cargo.toml
Labels: maintenance

#2146 fix: Remove profiling feature flag
  CHANGELOG.md
  relay-dynamic-config/src/feature.rs
  relay-server/src/actors/processor.rs
Labels: bug
