Repository getsentry/relay, pull requests merged in 2025-08, with the labels that each got.

#4940 feat(docker): Switch to a distroless base image
  CHANGELOG.md
  Dockerfile.release
  docker-entrypoint.sh
Labels: Trigger: Full-CI

#5017 ci(pr): Validate PR title to follow conventions
  .github/actions/changelog/index.js
Labels: skip-changelog

#5025 ref(filter): Add defaults to Filterable trait
  relay-filter/src/interface.rs
  relay-profiling/src/lib.rs
Labels: skip-changelog

#5029 feat(spanv2): Add experimental span v2 processing feature flag
  relay-dynamic-config/src/feature.rs
Labels: skip-changelog

#5047 ref(beta): Fixes latest beta lints
  relay-event-schema/src/protocol/security_report.rs
  relay-redis/src/pool.rs
  relay-server/src/utils/multipart.rs
Labels: skip-changelog

#5030 ref(rate-limits): Add convenience trait to rate limit by quantities
  relay-server/src/processing/limits.rs
  relay-server/src/processing/logs/mod.rs
Labels: skip-changelog

#5033 feat(spanv2): Basic implementation of a SpanV2 processor
  relay-server/src/processing/mod.rs
  relay-server/src/processing/spans/mod.rs
  relay-server/src/services/processor.rs
  relay-server/src/services/processor/dynamic_sampling.rs
  relay-server/src/services/processor/profile.rs
  relay-server/src/services/processor/report.rs
Labels: skip-changelog

#5035 ref(processing): Reduce code duplication for calling new processing
  relay-server/src/services/processor.rs
Labels: skip-changelog

#5056 build(prospero): Check version file instead of lib.rs
  relay-prosperoconv/Cargo.toml
  relay-prosperoconv/build.rs
Labels: skip-changelog

#5058 feat(spanv2): Implements metric extraction and improves dynamic sampling
  relay-server/src/managed/counted.rs
  relay-server/src/managed/managed.rs
  relay-server/src/managed/managed/debug.rs
  relay-server/src/metrics/outcomes.rs
  relay-server/src/processing/mod.rs
  relay-server/src/processing/spans/dynamic_sampling.rs
  relay-server/src/processing/spans/mod.rs
  relay-server/src/processing/spans/process.rs
  relay-server/src/services/processor.rs
  tests/integration/fixtures/mini_sentry.py
  tests/integration/fixtures/processing.py
  tests/integration/test_spans.py
  tests/integration/test_spansv2.py
Labels: skip-changelog

#5060 feat(devservices): Use ghcr instead of artifact registry
  devservices/config.yml
Labels: skip-changelog

#5074 fix(dep): Comment breaking release sh
  CHANGELOG.md
  scripts/docker-manylinux.sh
Labels: skip-changelog

#5078 feat(spanv2): Implements basic inbound filtering
  relay-event-schema/src/protocol/span_v2.rs
  relay-filter/src/interface.rs
  relay-server/src/processing/spans/filter.rs
  relay-server/src/processing/spans/mod.rs
  tests/integration/test_spansv2.py
Labels: skip-changelog

#5075 feat(ci): Use github composite action to build and push images
  .github/workflows/ci.yml
Labels: Trigger: Full-CI, skip-changelog

#5089 Revert "feat(ci): Use github composite action to build and push images"
  .github/workflows/ci.yml
Labels: skip-changelog

#5087 feat(spanv2): Implement basic eap attribute normalization
  relay-event-normalization/src/eap/mod.rs
  relay-event-normalization/src/event.rs
  relay-event-normalization/src/geo.rs
  relay-event-normalization/src/lib.rs
  relay-event-normalization/src/normalize/span/tag_extraction.rs
  relay-event-normalization/src/normalize/user_agent.rs
  relay-event-normalization/src/replay.rs
  relay-event-schema/src/protocol/attributes.rs
  relay-event-schema/src/protocol/span_v2.rs
  relay-server/src/extractors/request_meta.rs
  relay-server/src/processing/logs/process.rs
  relay-server/src/processing/spans/mod.rs
  relay-server/src/processing/spans/process.rs
  relay-server/src/services/processor.rs
  relay-server/src/services/processor/replay.rs
  relay-server/src/services/processor/span/processing.rs
  relay-spans/src/otel_to_sentry.rs
  tests/integration/test_spansv2.py
Labels: skip-changelog

#5092 ci(changelog): Allow more punctuation at the end of the `PR title`
  .github/actions/changelog/index.js
Labels: skip-changelog

#5090 feat(ci): Use github composite action to build and push images x2
  .github/workflows/ci.yml
Labels: Trigger: Full-CI, skip-changelog

#5093 test(spans): Snapshot for span backfill
  relay-server/src/services/store.rs
Labels: skip-changelog

#5099 fix(genai): Use correct pii maybe, not false
  relay-event-schema/src/protocol/span.rs
Labels: skip-changelog

#5100 test(spanv2): Slightly increase timeout to reduce flakes
  tests/integration/test_spansv2.py
Labels: skip-changelog
